version: "3.7"
services:
  db:
    image: mariadb:11.4.1-rc-jammy
    ports:
      - 3306:3306
    restart: always
    container_name: blog_db
    env_file:
      - .db.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    networks:
      - proxy

  redis:
    image: redis:7.0.15
    container_name: blog_redis
    restart: always
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/conf/redis.conf
      - ./redis_data:/data\
    command: redis-server --requirepass ${REDIS_PASS}
    env_file:
      - .redis.env
    labels:
      - "name=blog"
      - "mode=standalone"
    networks:
      - proxy
    
  app:
    depends_on: 
      - redis
      - db
    # image: ${REGISTRY_URL}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dong_ian_back
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 9482:9482
    volumes:
      - ./logs:/home/node/logs
    networks:
      - proxy
    
volumes:
  blog_minio_storage: {}
networks:
  proxy:
    external: true
